### ISSUE TITLE
Error on first run

### ISSUE THREAD

**Issue by jkmaxwell** [sebble/inky-frame-calendar#3]
I'm getting the following error on an inky frame:

```
>>> %Run -c $EDITOR_CONTENT

MPY: soft reboot
Traceback (most recent call last):
  File "<stdin>", line 10, in <module>
  File "ical.py", line 4, in <module>
ImportError: can't import name FUNCTION_URL
>>> 
```

changing / adding FUNCTION_URL to ICS_URL doesn't seem to solve it, because then it just hangs on boot.

**Comment by frdayeen** [comment]
I have the same problem. Changed the ICS_URL but it did not work.
